name: 🚀 Integração Contínua (CI) - Validação de Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout do Código-fonte
        uses: actions/checkout@v4
      - name: ⚙️ Configuração Ambiente Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: 📥 Instalação de Dependências (Angular)
        run: npm install --legacy-peer-deps
      - name: 🏗️ Build da Biblioteca GEMS SDK
        run: npm run build gems-sdk
      - name: 🏗️ Build do Showcase App
        run: npm run build gems-showcase
